server:
  port: 1518
spring:
  application:
    name: gixor-github
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.98.60:8848
        namespace: ${spring.profiles.active}
      config:
        server-addr: 39.105.98.60:8848
        file-extension: yml
  config:
    import: nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
